# 指定语言环境
language: node_js

# 指定需要sudo权限
sudo: required

node_js:
  - node

# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
  - $HOME/.npm
  - $HOME/lean

before_install:
  - wget https://attachments-cdn.shimo.im/g7nGwHs34Qk7C4O5/lean-linux-x64
  - mv lean-linux-x64 lean
  - chmod +x ./lean

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir:  dist
  keep_history: true
  on:
    branch: master
  fqdn: smc.wiki

after_deploy: 
  - npx vue-cli-service build --mode production --dest dist
  - ./lean login -u $LC_USER -p $LC_PASSWORD -r CN
  - ./lean switch SMC
  - ./lean deploy
  - ./lean publish